//Create forum
export const CREATE_FORUM_REQUEST = "CREATE_FORUM_REQUEST";
export const CREATE_FORUM_REQUEST_SUCCESS = "CREATE_FORUM_REQUEST_SUCCESS";
export const CREATE_FORUM_REQUEST_ERROR = "CREATE_FORUM_REQUEST_ERROR";

//Loader
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
