//Create forum
export const CREATE_FORUM_REQUEST = "CREATE_FORUM_REQUEST";
export const CREATE_FORUM_REQUEST_SUCCESS = "CREATE_FORUM_REQUEST_SUCCESS";
export const CREATE_FORUM_REQUEST_ERROR = "CREATE_FORUM_REQUEST_ERROR";

//Get forums
export const GET_FORUMS_REQUEST = "GET_FORUMS_REQUEST";
export const GET_FORUMS_REQUEST_SUCCESS = "GET_FORUMS_REQUEST_SUCCESS";
export const GET_FORUMS_REQUEST_ERROR = "GET_FORUMS_REQUEST_ERROR";

//Delete forum
export const DELETE_FORUM_REQUEST = "DELETE_FORUM_REQUEST";
export const DELETE_FORUM_REQUEST_SUCCESS = "DELETE_FORUM_REQUEST_SUCCESS";
export const DELETE_FORUM_REQUEST_ERROR = "DELETE_FORUM_REQUEST_ERROR";

//Create topic
export const CREATE_TOPIC_REQUEST = "CREATE_TOPIC_REQUEST";
export const CREATE_TOPIC_REQUEST_SUCCESS = "CREATE_TOPIC_REQUEST_SUCCESS";
export const CREATE_TOPIC_REQUEST_ERROR = "CREATE_TOPIC_REQUEST_ERROR";

//Delete topic
export const DELETE_TOPIC_REQUEST = "DELETE_TOPIC_REQUEST";
export const DELETE_TOPIC_REQUEST_SUCCESS = "DELETE_TOPIC_REQUEST_SUCCESS";
export const DELETE_TOPIC_REQUEST_ERROR = "DELETE_TOPIC_REQUEST_ERROR";

//Get topics
export const GET_TOPICS_REQUEST = "GET_TOPICS_REQUEST";
export const GET_TOPICS_REQUEST_SUCCESS = "GET_TOPICS_REQUEST_SUCCESS";
export const GET_TOPICS_REQUEST_ERROR = "GET_TOPICS_REQUEST_ERROR";

//Search topics by name
export const SEARCH_TOPICS_REQUEST = "SEARCH_TOPICS_REQUEST";
export const SEARCH_TOPICS_REQUEST_SUCCESS = "SEARCH_TOPICS_REQUEST_SUCCESS";
export const SEARCH_TOPICS_REQUEST_ERROR = "SEARCH_TOPICS_REQUEST_ERROR";

//Create reply
export const CREATE_REPLY_REQUEST = "CREATE_REPLY_REQUEST";
export const CREATE_REPLY_REQUEST_SUCCESS = "CREATE_REPLY_REQUEST_SUCCESS";
export const CREATE_REPLY_REQUEST_ERROR = "CREATE_REPLY_REQUEST_ERROR";

//Set active forum id
export const SET_ACTIVE_FORUM_ID = "SET_ACTIVE_FORUM_ID";
export const SET_ACTIVE_FORUM_ID_SUCCESS = "SET_ACTIVE_FORUM_ID_SUCCESS";


//Loader
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
