//Create forum
export const CREATE_FORUM_REQUEST = "CREATE_FORUM_REQUEST";
export const CREATE_FORUM_REQUEST_SUCCESS = "CREATE_FORUM_REQUEST_SUCCESS";
export const CREATE_FORUM_REQUEST_ERROR = "CREATE_FORUM_REQUEST_ERROR";

//Get forums
export const GET_FORUMS_REQUEST = "GET_FORUMS_REQUEST";
export const GET_FORUMS_REQUEST_SUCCESS = "GET_FORUMS_REQUEST_SUCCESS";
export const GET_FORUMS_REQUEST_ERROR = "GET_FORUMS_REQUEST_ERROR";

//Delete forum
export const DELETE_FORUM_REQUEST = "DELETE_FORUM_REQUEST";
export const DELETE_FORUM_REQUEST_SUCCESS = "DELETE_FORUM_REQUEST_SUCCESS";
export const DELETE_FORUM_REQUEST_ERROR = "DELETE_FORUM_REQUEST_ERROR";

//Create topic
export const CREATE_TOPIC_REQUEST = "CREATE_TOPIC_REQUEST";
export const CREATE_TOPIC_REQUEST_SUCCESS = "CREATE_TOPIC_REQUEST_SUCCESS";
export const CREATE_TOPIC_REQUEST_ERROR = "CREATE_TOPIC_REQUEST_ERROR";

//Delete topic
export const DELETE_TOPIC_REQUEST = "DELETE_TOPIC_REQUEST";
export const DELETE_TOPIC_REQUEST_SUCCESS = "DELETE_TOPIC_REQUEST_SUCCESS";
export const DELETE_TOPIC_REQUEST_ERROR = "DELETE_TOPIC_REQUEST_ERROR";

//Get topics
export const GET_TOPICS_REQUEST = "GET_TOPICS_REQUEST";
export const GET_TOPICS_REQUEST_SUCCESS = "GET_TOPICS_REQUEST_SUCCESS";
export const GET_TOPICS_REQUEST_ERROR = "GET_TOPICS_REQUEST_ERROR";

//Search topics by name
export const SEARCH_TOPICS_REQUEST = "SEARCH_TOPICS_REQUEST";
export const SEARCH_TOPICS_REQUEST_SUCCESS = "SEARCH_TOPICS_REQUEST_SUCCESS";
export const SEARCH_TOPICS_REQUEST_ERROR = "SEARCH_TOPICS_REQUEST_ERROR";

//Create reply
export const CREATE_REPLY_REQUEST = "CREATE_REPLY_REQUEST";
export const CREATE_REPLY_REQUEST_SUCCESS = "CREATE_REPLY_REQUEST_SUCCESS";
export const CREATE_REPLY_REQUEST_ERROR = "CREATE_REPLY_REQUEST_ERROR";

//Get replies
export const GET_REPLIES_REQUEST = "GET_REPLIES_REQUEST";
export const GET_REPLIES_REQUEST_SUCCESS = "GET_REPLIES_REQUEST_SUCCESS";
export const GET_REPLIES_REQUEST_ERROR = "GET_REPLIES_REQUEST_ERROR";

//Get user posts number
export const GET_USER_POSTS_REQUEST = "GET_USER_POSTS_REQUEST";
export const GET_USER_POSTS_REQUEST_SUCCESS = "GET_USER_POSTS_REQUEST";

//Set active forum id
export const SET_ACTIVE_FORUM_ID = "SET_ACTIVE_FORUM_ID";
export const SET_ACTIVE_FORUM_ID_SUCCESS = "SET_ACTIVE_FORUM_ID_SUCCESS";

//Like/unlike reply
export const LIKE_UNLIKE_REPLY = "LIKE_UNLIKE_REPLY";
export const LIKE_UNLIKE_REPLY_SUCCESS = "LIKE_UNLIKE_REPLY_SUCCESS";
export const LIKE_UNLIKE_REPLY_ERROR = "LIKE_UNLIKE_REPLY_ERROR";

//Loader
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";


//Reseters
export const RESET_FORUMS = "RESET_FORUMS";
